### PR TITLE
Use slightly modified llvm interpreter instead of using our own 

### PR DESCRIPTION
**Pull request by undingen**
This is not ready to be merged.
It's just a test to see how hard it would be to use a slightly modified version of the builtin llvm interpreter.
And it looks like it shouldn't be to hard/not many modifications are needed :-).

This could be something to think about in the future when we need more instructions/vector types etc..

This is able to run prime_summing and fib2 with tracing.

### CODE REVIEW

**Comment by kmod** [comment]
I like it!

**Comment by undingen** [comment]
Ok I pushed a new cleaned up version which changed a lot to the first WIP version:

I tried to make as little changes as possible to the copied LLVM Interpreter while still supporting everything of dpro.
    
Also I used as much as possible of the llvm implementations
e.g. `loadPointer()` is now calling directly into `ExecutionEngine::LoadValueFromMemory`.
This unfortunately also added a dependency of `LLVMJit` to the interpreter that's why I added a new class `LLVMEvaluator` which allows `LLVMJit` to call into the interpreter.
    
While this does not yet support types which don't fit into longs or have different calling conventions (external calls are not yet correct) this should bring us much closer. And removes a ton of code :-).
    
One small change which may changes the number of BBs is that we now always split the basic block around the original call instruction because it makes it easier to resume interpreting.
    
I verified manually that `pytest1`, `prime_summing` and `fib2` inline the same functions.

Sorry that this patch is a bit hard to review because it changes so much code...

**Comment by undingen** [comment]
Ah also this tries now to correctly use `GenericValue` (in the previous version I just pretended everything is a pointer and stuffed everything in there. Now instead I use the correct field in the struct depending on the type.)

This also adds support for correctly printing the inline sources (`printCurrentInlineSource()`) which the WIP version did not support.

**Comment by undingen** [comment]
Wait I just found a bug - this is miscompiling `test1`. I will take a look

**Comment by undingen** [comment]
Fixed in last commit:
Fix calls where num args != params and don't let llvm handle the GV initializers
this fixes 'test1'.
First problem was that we did not pass all values to the printf call.
Second that the interpreter embedded a reference to a memory location which gets freed when the module is destroyed.

This also adds some asserts to catch if a function expects a float which we currently don't handle because of the different calling convention...

**Comment by kmod** [comment]
Looks pretty good!

I noticed though that it's crashing on `make bm_nbody`, I'm not sure why.  (On master bm_nbody crashes during jitting but on this branch it crashes now in interpreting.)

**Comment by undingen** [comment]
Thanks for letting me know of the problem!
It took me quite a while to find the issue but I fixed it now - take a look at the last commit.
(I did not rebase it yet. Because I would also like to squash the last three commits together but wanted to make it easier to see what I had to change to fix the issue):

__Fix bm_nbody: the interpreter did not correctly handle comparisons of function pointers__
This was caused by `getPointerToFunction(Function* F){ return F; }`

Inside `object_new` is the following comparison: `type->tp_new != object_new`
Because the interpreter did not resolve functions to there actual machine code address this comparison was actual comparing
`type->tp_new (address to machine code) != object_new(llvm::Function* not the machine code address!)`

Good thing is that now that I know what the problem is it actually simplifies a bunch of code :-)

**Comment by kmod** [comment]
Looks good to me!

**Comment by undingen** [comment]
squashed and rebased - ready for merging.

**Comment by kmod** [comment]
Awesome, glad we don't have to maintain our own interpreter anymore :)

**Pull request merged**
